### ISSUE TITLE
Прозрачность API

### ISSUE THREAD

**Issue by alexmikhalevich** [Mrkol/hw_cards#2]
Я правильно понимаю, что мне как заказчику предлагается повторить код теста чтобы воплотить в жизнь этот юзкейс? https://github.com/Mrkol/hw_cards/blob/0f17aa404d96cf8581ebbb45848e2a0e20ad5812/tests/general_tests.cpp#L32

**Comment by Mrkol** [comment]
API было разработано для _считывания_ карт. Запись паспортных данных не входила в ТЗ.

**Comment by alexmikhalevich** [comment]
а, я понял  
ок
